dist: xenial
language: c
addons:
  apt:
    packages:
    - mkdocs
cache:
  directories:
    - crayon-architect/cache
before_script:
  - cd $TRAVIS_BUILD_DIR
  - crayon-architect/clean.sh
script:
  - cd $TRAVIS_BUILD_DIR
  - crayon-architect/build.sh
after_success:
  - cd $TRAVIS_BUILD_DIR
  - crayon-architect/deploy.sh

