site_name: RTFM
site_dir: /var/www/rtfm/ 
#pages:
#    - Home: index.md
#    - Docs:
#      - Documentation: docs.md
#      - c220: c220.md
#      - Flatline: flatline.md
#      - lxd-member-boxes: lxd-member-boxes-faq.md
#      - Motioneye: motioneye.md
#      - Pi-Hole & Stubby: pi-hole-stubby.md
#      - Unifi: unifi.md
